# Generated by Django 4.2.30 on 2026-06-21 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_student_profile_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine_name', models.CharField(help_text='e.g. COVID-19, BCG, MMR, Polio, HPV, Hepatitis B', max_length=150)),
                ('vaccination_date', models.DateField()),
                ('dose_number', models.PositiveSmallIntegerField(default=1, help_text='1 = first dose, 2 = second dose, 3 = booster, etc.')),
                ('administered_by', models.CharField(blank=True, help_text='Clinic name, health worker, or government campaign — not a system user', max_length=200)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('next_due_date', models.DateField(blank=True, help_text='Date next dose or booster is due — surfaces as alert on health dashboard', null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='School staff who entered this record into the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_records_entered', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Vaccination Record',
                'db_table': 'health_vaccination_record',
                'ordering': ['vaccine_name', 'dose_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies — cross-checked against canteen MenuItem.contains_allergens')),
                ('chronic_conditions', models.TextField(blank=True, help_text='e.g. asthma, diabetes, epilepsy, sickle cell — informs teacher and nurse response')),
                ('physical_disabilities', models.TextField(blank=True)),
                ('is_on_regular_medication', models.BooleanField(default=False)),
                ('regular_medication_details', models.TextField(blank=True, help_text='Name, dosage, and schedule of ongoing daily medications')),
                ('special_dietary_requirements', models.TextField(blank=True, help_text='Medical dietary needs — surfaced on canteen weekly menu for flagged students')),
                ('emergency_contact_1_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_1_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_1_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_2_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_2_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_2_relationship', models.CharField(blank=True, max_length=50)),
                ('doctor_name', models.CharField(blank=True, max_length=150)),
                ('doctor_phone', models.CharField(blank=True, max_length=20)),
                ('hospital_preference', models.CharField(blank=True, help_text='Preferred hospital or clinic in case of emergency', max_length=200)),
                ('medical_insurance_provider', models.CharField(blank=True, max_length=150)),
                ('medical_insurance_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records_updated', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_record', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Student Health Record',
                'db_table': 'health_student_health_record',
            },
        ),
        migrations.CreateModel(
            name='NurseVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit_type', models.CharField(choices=[('illness', 'Illness'), ('injury', 'Injury'), ('routine_check', 'Routine Check'), ('emergency', 'Emergency'), ('follow_up', 'Follow-Up Visit')], default='illness', max_length=15)),
                ('complaint', models.TextField(help_text='Student-reported reason for visit')),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in °C — flag if >37.5', max_digits=4, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='e.g. 120/80 mmHg', max_length=20)),
                ('symptoms', models.TextField(blank=True, help_text='Nurse-observed symptoms')),
                ('assessment', models.TextField(blank=True, help_text='Nurse clinical assessment / diagnosis')),
                ('action_taken', models.CharField(choices=[('returned_to_class', 'Returned to Class'), ('sent_home', 'Sent Home'), ('referred_hospital', 'Referred to Hospital'), ('observation', 'Kept Under Observation'), ('referred_counsellor', 'Referred to Counsellor'), ('other', 'Other')], default='returned_to_class', max_length=22)),
                ('parent_notified', models.BooleanField(default=False)),
                ('parent_notified_time', models.DateTimeField(blank=True, help_text='Auto-set when parent_notified is first ticked', null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('attended_by', models.ForeignKey(blank=True, help_text='Nurse or staff member who attended the student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_visits_attended', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_visits', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Nurse Visit',
                'db_table': 'health_nurse_visit',
                'ordering': ['-visit_datetime'],
            },
        ),
        migrations.CreateModel(
            name='MedicationDispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(help_text='e.g. 500 mg, 2 tablets', max_length=100)),
                ('quantity_dispensed', models.CharField(help_text='e.g. 2 tablets, 5 ml', max_length=50)),
                ('time_dispensed', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_school_stock', models.BooleanField(default=True, help_text='True = dispensed from school medical store; False = from student-provided supply')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications_dispensed_by', to=settings.AUTH_USER_MODEL)),
                ('nurse_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications_dispensed', to='health.nursevisit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Medication Dispensing Record',
                'db_table': 'health_medication_dispensing',
                'ordering': ['time_dispensed'],
            },
        ),
    ]
