# Generated by Django 4.2.30 on 2026-06-15 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('staff_hr', '0001_initial'),
        ('core', '0001_initial'),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClearanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('library', 'Library'), ('finance', 'Finance / Accounts'), ('academics', 'Academic Registrar'), ('sports', 'Sports / PE'), ('health', 'Health / Nurse'), ('hostel', 'Hostel / Boarding'), ('it', 'ICT Department'), ('custom', 'Other Department')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_status', models.CharField(choices=[('in_progress', 'In Progress'), ('cleared', 'Cleared'), ('blocked', 'Blocked')], default='in_progress', max_length=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-academic_year__start_date'],
                'unique_together': {('tenant', 'student', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='TermEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New Student'), ('continuing', 'Continuing Student'), ('retake', 'Completed with Retakes'), ('deferral', 'Deferred / Dead Year'), ('completed', 'Programme Completed')], default='continuing', max_length=20)),
                ('study_year', models.PositiveSmallIntegerField(help_text='Year of study (1, 2, 3…)')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_term_enrollments', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_term_enrollments', to='core.term')),
            ],
            options={
                'verbose_name': 'Term Enrollment',
                'ordering': ['-term__start_date'],
                'unique_together': {('tenant', 'student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='ProgramChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text="Student's stated reason for the change")),
                ('supporting_document', models.CharField(blank=True, help_text='Cloudinary file path', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('current_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_from', to='students.classroom')),
                ('requested_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_to', to='students.classroom')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_hr.staffprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_changes', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Programme Change Request',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('finance', 'Finance'), ('attendance', 'Attendance'), ('discipline', 'Discipline'), ('welfare', 'Welfare'), ('document', 'Document Ready'), ('system', 'System'), ('general', 'General')], default='general', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('action_url', models.CharField(blank=True, help_text='Portal URL to navigate to', max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_notifications', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveOfAbsenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('medical', 'Medical Leave'), ('financial', 'Financial Hardship'), ('personal', 'Personal Reasons'), ('bereavement', 'Bereavement'), ('official', 'Official / Scholarship'), ('other', 'Other')], max_length=15)),
                ('reason', models.TextField()),
                ('supporting_document', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reinstated', 'Reinstated')], default='pending', max_length=12)),
                ('admin_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_return_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_return', to='core.term')),
                ('from_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_from', to='core.term')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_hr.staffprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Leave of Absence Request',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('blocked', 'Blocked — Clearance Incomplete'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.TextField(blank=True, help_text='Reason if blocked (e.g. unpaid fees)')),
                ('pdf_path', models.CharField(blank=True, help_text='Cloudinary PDF path', max_length=500)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_permit', to='student_portal.termenrollment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Exam Permit',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_type', models.CharField(choices=[('remark', 'Re-mark Request'), ('clerical', 'Clerical Error'), ('missing', 'Missing Result'), ('query', 'General Query')], max_length=15)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='submitted', max_length=15)),
                ('original_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('statement', models.TextField(help_text="Student's written grounds for the appeal")),
                ('admin_response', models.TextField(blank=True)),
                ('revised_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_hr.staffprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_appeals', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term')),
            ],
            options={
                'verbose_name': 'Exam Appeal',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('term_start', 'Term / Semester Start'), ('term_end', 'Term / Semester End'), ('exam_period', 'Examination Period'), ('registration', 'Registration Window'), ('fee_deadline', 'Fee Payment Deadline'), ('holiday', 'Public Holiday / Break'), ('submission', 'Assignment / Project Deadline'), ('graduation', 'Graduation / Prize Day'), ('sports', 'Sports Day / Competition'), ('open_day', 'Open Day / Visiting Day'), ('announcement', 'General School Event')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for single-day events', null=True)),
                ('audience', models.CharField(choices=[('all', 'All Students'), ('primary', 'Primary Only'), ('secondary', 'Secondary Only'), ('tertiary', 'Tertiary Only'), ('class', 'Specific Class/Year')], default='all', max_length=15)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_hr.staffprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.term')),
            ],
            options={
                'verbose_name': 'Academic Calendar Event',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentClearanceItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('blocked', 'Blocked'), ('waived', 'Waived')], default='pending', max_length=10)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_statuses', to='student_portal.studentclearance')),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_hr.staffprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_portal.academicclearanceitem')),
            ],
            options={
                'ordering': ['item__order'],
                'unique_together': {('clearance', 'item')},
            },
        ),
        migrations.CreateModel(
            name='CourseUnitRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(choices=[('normal', 'Normal Paper'), ('retake', 'Retake'), ('supplementary', 'Supplementary'), ('missed', 'Missed Paper'), ('elective', 'Elective Subject')], default='normal', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='student_portal.termenrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='academics.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Course Unit Registration',
                'ordering': ['subject__name'],
                'unique_together': {('tenant', 'enrollment', 'subject')},
            },
        ),
    ]
