# Generated by Django 4.2.30 on 2026-06-21 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=15)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_plans', to='core.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_plans_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_plans_created', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Training Plan',
                'db_table': 'staff_training_plan',
                'ordering': ['-academic_year__start_date'],
                'unique_together': {('tenant', 'staff_member', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='TrainingPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training_title', models.CharField(max_length=255)),
                ('training_type', models.CharField(choices=[('internal_workshop', 'Internal Workshop'), ('external_course', 'External Course'), ('online_learning', 'Online Learning'), ('conference', 'Conference / Seminar'), ('mentoring', 'Peer Mentoring'), ('peer_observation', 'Peer Observation'), ('other', 'Other')], default='external_course', max_length=20)),
                ('provider', models.CharField(blank=True, help_text='Training provider, institution, or platform name', max_length=200)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('cost_ugx', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated or actual cost in UGX', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=10)),
                ('outcome', models.TextField(blank=True, help_text='What was learned / achieved — filled in after completion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='staff_hr.trainingplan')),
            ],
            options={
                'verbose_name': 'Training Plan Item',
                'db_table': 'staff_training_plan_item',
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appraisal_period', models.CharField(help_text="e.g. 'Annual 2024-25', 'Mid-Year Term 2 2025'", max_length=50)),
                ('appraisal_date', models.DateField()),
                ('teaching_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('punctuality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student_relations', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('professional_dev', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('teamwork', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('appraiser_comments', models.TextField(blank=True)),
                ('staff_response', models.TextField(blank=True, help_text='Staff member can respond before the record is formally acknowledged')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to HR'), ('acknowledged', 'Acknowledged by Staff')], default='draft', max_length=15)),
                ('acknowledged_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_appraisals', to='core.academicyear')),
                ('appraiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisals_conducted', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals_received', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Staff Appraisal',
                'db_table': 'staff_appraisal',
                'ordering': ['-appraisal_date'],
                'unique_together': {('tenant', 'staff_member', 'academic_year', 'appraisal_period')},
            },
        ),
        migrations.CreateModel(
            name='AppraisalObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objective', models.TextField()),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('achieved', 'Achieved'), ('not_achieved', 'Not Achieved')], default='pending', max_length=15)),
                ('evidence', models.TextField(blank=True, help_text='Evidence provided by staff member')),
                ('review_notes', models.TextField(blank=True, help_text='Reviewer notes at next appraisal cycle')),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='staff_hr.staffappraisal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Appraisal Objective',
                'db_table': 'staff_appraisal_objective',
                'ordering': ['target_date'],
            },
        ),
    ]
