# Generated by Django 4.2.30 on 2026-06-21 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_student_profile_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_phone', models.CharField(blank=True, max_length=20)),
                ('visitor_id_number', models.CharField(blank=True, max_length=50)),
                ('expected_date', models.DateField()),
                ('expected_time_from', models.TimeField(blank=True, null=True)),
                ('expected_time_to', models.TimeField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Expected'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expected_visitors_registered', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, help_text='Set when a parent pre-registers a visit to see their child', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expected_visitors', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Expected Visitor',
                'db_table': 'visitor_expected_visitor',
                'ordering': ['expected_date', 'expected_time_from'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('id_type', models.CharField(choices=[('nin', 'National ID (NIN)'), ('passport', 'Passport'), ('dl', 'Drivers Licence'), ('other', 'Other')], default='nin', max_length=10)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged visitors trigger an alert at reception — do not allow entry without principal approval')),
                ('flag_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('flag_added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_flagged', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Visitor',
                'db_table': 'visitor_visitor',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('parent_visit', 'Parent / Guardian Visit'), ('delivery', 'Delivery'), ('contractor', 'Contractor / Maintenance'), ('interview', 'Interview / Recruitment'), ('official', 'Official / Government'), ('vendor', 'Vendor'), ('other', 'Other')], max_length=15)),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('badge_number', models.CharField(blank=True, editable=False, max_length=20)),
                ('items_carried', models.CharField(blank=True, help_text='e.g. laptop bag, toolbox, parcels — logged for security', max_length=255)),
                ('vehicle_registration', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('checked_in', 'Currently On-Site'), ('checked_out', 'Checked Out'), ('overstay', 'Overstay Alert')], default='checked_in', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('expected_visitor', models.ForeignKey(blank=True, help_text='Linked pre-registration record, if visitor was expected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_visits', to='visitor.expectedvisitor')),
                ('host', models.ForeignKey(blank=True, help_text='Staff member being visited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_hosted', to=settings.AUTH_USER_MODEL)),
                ('signed_in_by', models.ForeignKey(blank=True, help_text='Receptionist who processed this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs_signed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, help_text='Student being visited — set for parent/guardian visits', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_visits', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_logs', to='visitor.visitor')),
            ],
            options={
                'verbose_name': 'Visitor Log Entry',
                'db_table': 'visitor_log',
                'ordering': ['-check_in_time'],
            },
        ),
    ]
