# Generated by Django 4.2.30 on 2026-07-22 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0002_student_profile_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='id_scan_raw',
            field=models.TextField(blank=True, help_text='Raw decoded MRZ/barcode payload from a camera-based ID scan, kept for audit and re-parsing — full_name/id_number above are the parsed fields'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Captured at first check-in — printed on the visitor badge', null=True, upload_to='visitors/photos/'),
        ),
        migrations.CreateModel(
            name='VisitorWatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('reason', models.CharField(choices=[('custody_dispute', 'Custody Dispute / Court Order'), ('expelled_staff', 'Former Staff — Dismissed'), ('security_threat', 'Security Threat'), ('other', 'Other')], default='other', max_length=20)),
                ('reason_detail', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist_entries_added', to=settings.AUTH_USER_MODEL)),
                ('related_student', models.ForeignKey(blank=True, help_text='Set when the restriction applies to one specific child only (e.g. a custody order) — leave blank for a school-wide ban', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_watchlist_entries', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Visitor Watchlist Entry',
                'verbose_name_plural': 'Visitor Watchlist Entries',
                'db_table': 'visitor_watchlist_entry',
                'ordering': ['full_name'],
            },
        ),
    ]
