# Generated by Django 4.2.30 on 2026-06-21 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_student_profile_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Cached balance — authoritative source is the MealTransaction ledger', max_digits=10)),
                ('low_balance_threshold', models.DecimalField(decimal_places=2, default=5000, help_text='Below this amount, a low-balance alert is triggered to the guardian', max_digits=10)),
                ('allow_overdraft', models.BooleanField(default=False, help_text='If true, deductions are allowed to push balance negative')),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_account', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Meal Account',
                'db_table': 'canteen_meal_account',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('beverage', 'Beverage')], default='lunch', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Amount deducted from the meal wallet per serving', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('contains_allergens', models.CharField(blank=True, help_text='Comma-separated allergens — cross-check against Student.allergies before serving', max_length=200)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'db_table': 'canteen_menu_item',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MealTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('top_up', 'Top-Up (Credit)'), ('deduction', 'Meal Deduction (Debit)'), ('refund', 'Refund (Credit)'), ('adjustment', 'Manual Adjustment')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('card', 'Card'), ('system', 'System (Automatic Meal Deduction)')], default='cash', max_length=15)),
                ('reference', models.CharField(blank=True, help_text='MoMo/card transaction reference, if applicable', max_length=100)),
                ('balance_after', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('meal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='canteen.mealaccount')),
                ('menu_item', models.ForeignKey(blank=True, help_text='Set only for deductions tied to a specific meal sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='canteen.menuitem')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canteen_transactions_recorded', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Meal Transaction',
                'db_table': 'canteen_meal_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start_date', models.DateField(help_text='Monday of the published week')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10)),
                ('published', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(blank=True, related_name='weekly_menus', to='canteen.menuitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Weekly Menu',
                'db_table': 'canteen_weekly_menu',
                'ordering': ['week_start_date', 'day'],
                'unique_together': {('tenant', 'week_start_date', 'day')},
            },
        ),
    ]
