# Generated by Django 4.2.30 on 2026-05-30 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Class Level Name')),
                ('short_name', models.CharField(blank=True, max_length=10, verbose_name='Short Name e.g. P1')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sort order')),
                ('category', models.CharField(choices=[('nursery', 'Nursery / Pre-Primary'), ('primary', 'Primary'), ('secondary', 'Secondary / High School'), ('college', 'College / University')], default='primary', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Class Level',
                'db_table': 'students_class_level',
                'ordering': ['order', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream', models.CharField(blank=True, help_text='e.g. East, Blue, A, North', max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=45)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='core.academicyear')),
                ('class_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='students.classlevel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Classroom',
                'db_table': 'students_classroom',
                'ordering': ['level__order', 'stream'],
                'unique_together': {('tenant', 'level', 'stream', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(help_text='Auto-generated by school format', max_length=20, verbose_name='Student ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, help_text='Name used daily if different', max_length=100)),
                ('nsin', models.CharField(blank=True, max_length=50, verbose_name='National Student Identification Number (NSIN)')),
                ('birth_cert_number', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Prefer not to say')], default='M', max_length=1)),
                ('nationality', models.CharField(default='Ugandan', max_length=50)),
                ('religion', models.CharField(blank=True, choices=[('christian', 'Christian'), ('muslim', 'Muslim'), ('other', 'Other'), ('none', 'None / Not stated')], max_length=20)),
                ('home_district', models.CharField(blank=True, max_length=100)),
                ('home_village', models.CharField(blank=True, max_length=100)),
                ('has_disability', models.BooleanField(default=False)),
                ('disability_type', models.CharField(blank=True, max_length=100)),
                ('is_orphan', models.BooleanField(default=False)),
                ('orphan_type', models.CharField(blank=True, choices=[('both', 'Double Orphan (both parents)'), ('father', 'Paternal Orphan'), ('mother', 'Maternal Orphan')], max_length=20)),
                ('is_refugee', models.BooleanField(default=False)),
                ('receives_bursary', models.BooleanField(default=False)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('medical_notes', models.TextField(blank=True, help_text='Any chronic conditions or medication requirements')),
                ('student_phone', models.CharField(blank=True, help_text="Student's own phone (secondary only)", max_length=20)),
                ('student_email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('status', models.CharField(choices=[('active', 'Active / Enrolled'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('expelled', 'Expelled'), ('deceased', 'Deceased'), ('deferred', 'Deferred')], default='active', max_length=15)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_reason', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('user', models.OneToOneField(blank=True, help_text='Portal login account for this student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students_student',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('tenant', 'student_id')},
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('sibling', 'Older Sibling'), ('guardian', 'Legal Guardian'), ('other', 'Other')], max_length=20)),
                ('phone_primary', models.CharField(max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact for this student')),
                ('is_fee_payer', models.BooleanField(default=False, help_text='Responsible for fee payments')),
                ('receives_sms', models.BooleanField(default=True)),
                ('receives_reports', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='Portal login account for this parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students_guardian',
                'ordering': ['-is_primary', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_repeating', models.BooleanField(default=False, help_text='True if student is repeating this class level')),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'db_table': 'students_enrollment',
                'ordering': ['-academic_year__start_date'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
