# Generated by Django 4.2.30 on 2026-06-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_verified',
            field=models.BooleanField(default=False, help_text='Admin has verified student biodata'),
        ),
    ]
