# Generated by Django 4.2.30 on 2026-08-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='refugee_or_pass_id',
            field=models.CharField(blank=True, default='', help_text='Refugee ID number or special student pass number, for refugee/asylum students.', max_length=50, verbose_name='Refugee ID / student pass number'),
        ),
    ]
