# Generated by Django 4.2.30 on 2026-05-30 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='School Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Subdomain')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('motto', models.CharField(blank=True, max_length=200)),
                ('school_type', models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('combined', 'Combined (P+S)'), ('university', 'University / College'), ('vocational', 'Vocational / Technical'), ('nursery', 'Nursery / Pre-Primary')], default='primary', max_length=20)),
                ('country', models.CharField(default='Uganda', max_length=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#1B3A6B', max_length=7)),
                ('secondary_color', models.CharField(default='#0A7B8C', max_length=7)),
                ('custom_domain', models.CharField(blank=True, help_text='Custom domain e.g. sms.stamarys.ac.ug', max_length=200)),
                ('plan', models.CharField(choices=[('trial', 'Free Trial'), ('starter', 'Starter (≤300 students)'), ('growth', 'Growth (≤800 students)'), ('professional', 'Professional (≤2000 students)'), ('network', 'Network / School Group'), ('government', 'Government / EMIS')], default='trial', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('grace_period', 'Grace Period'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('plan_end', models.DateTimeField(blank=True, null=True)),
                ('emis_code', models.CharField(blank=True, max_length=50, verbose_name='EMIS School Code')),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tenant (School)',
                'verbose_name_plural': 'Tenants (Schools)',
                'db_table': 'core_tenant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='e.g. 2024/2025')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'db_table': 'core_academic_year',
                'ordering': ['-start_date'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('term_1', 'Term 1'), ('term_2', 'Term 2'), ('term_3', 'Term 3')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.academicyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.tenant')),
            ],
            options={
                'db_table': 'core_term',
                'ordering': ['academic_year', 'name'],
                'unique_together': {('academic_year', 'name')},
            },
        ),
    ]
