# Generated by Django 4.2.30 on 2026-08-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='emis_country',
            field=models.CharField(blank=True, choices=[('uganda_moes', 'Uganda (MoES)'), ('kenya_moe', 'Kenya (MoE / KEMIS)'), ('rwanda_reb', 'Rwanda (REB)'), ('tanzania_moevt', 'Tanzania (MoEST / ESMIS)')], help_text='Controls which ministry export format and registration fields apply.', max_length=20, verbose_name='EMIS Reporting Country'),
        ),
    ]
