# Generated by Django 4.2.30 on 2026-08-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_emis_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_method',
            field=models.CharField(blank=True, choices=[('pesapal_card', 'Card (PesaPal, auto-renews)'), ('mtn_momo', 'MTN Mobile Money (renewal prompt)'), ('airtel', 'Airtel Money (renewal prompt)'), ('bank', 'Bank Transfer (manual)'), ('manual', 'Manual / Platform Admin')], help_text='Which rail this tenant renews through — decides whether the daily billing task attempts a silent charge or sends a prompt.', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='grace_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
