# Generated by Django 4.2.30 on 2026-08-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_billing_method_tenant_grace_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='deletion_warning_sent_at',
            field=models.DateTimeField(blank=True, help_text='Set once, the first time the 60-day suspension deletion warning goes out — stops the daily sweep re-sending it every day after.', null=True),
        ),
    ]
