# Generated by Django 4.2.30 on 2026-08-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant_deletion_warning_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Manual discount (0-100) applied by a platform admin — Section 5.4.'),
        ),
    ]
