# Generated by Django 4.2.30 on 2026-07-04 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_profile_verified'),
        ('core', '0001_initial'),
        ('staff_hr', '0002_trainingplan_trainingplanitem_staffappraisal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(help_text='Used if driver is not also a Staff user', max_length=128)),
                ('phone', models.CharField(max_length=32)),
                ('license_number', models.CharField(max_length=64)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32)),
                ('shift', models.CharField(choices=[('AM', 'Morning Pickup'), ('PM', 'Afternoon Drop-off'), ('BOTH', 'Both')], default='BOTH', max_length=8)),
                ('planned_path', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='transport.driver')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=128)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('scheduled_time', models.TimeField()),
                ('radius_meters', models.PositiveIntegerField(default=150, help_text='Geofence radius for arrival detection')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.route')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(max_length=32)),
                ('make', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('capacity', models.PositiveIntegerField(help_text='Number of student seats')),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('ELECTRIC', 'Electric')], default='DIESEL', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'In Maintenance'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=16)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('road_license_expiry', models.DateField(blank=True, null=True)),
                ('inspection_expiry', models.DateField(blank=True, null=True)),
                ('gps_device_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('AM', 'Morning Pickup'), ('PM', 'Afternoon Drop-off'), ('BOTH', 'Both')], max_length=8)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='transport.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='transport.route')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='transport.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTransportAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dropoff_stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoffs', to='transport.stop')),
                ('pickup_stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='transport.stop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='transport.route')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RouteDeviationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('OFF_ROUTE', 'Off Planned Route'), ('LATE', 'Running Late'), ('SPEED', 'Speed Violation'), ('UNSCHEDULED_STOP', 'Unscheduled Stop')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('distance_meters', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='transport.triplog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='transport.vehicle'),
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_type', models.CharField(choices=[('INSPECTION', 'Inspection'), ('SERVICE', 'Routine Service'), ('REPAIR', 'Repair')], max_length=16)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('performed_at', models.DateField()),
                ('next_due_at', models.DateField(blank=True, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=128)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='transport.vehicle')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='transport.vehicle'),
        ),
        migrations.AddField(
            model_name='driver',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to='staff_hr.staffprofile'),
        ),
        migrations.AddField(
            model_name='driver',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='BoardingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('BOARD', 'Boarded'), ('ALIGHT', 'Alighted')], max_length=8)),
                ('method', models.CharField(choices=[('RFID', 'RFID Card'), ('QR', 'QR Code'), ('MANUAL', 'Manual Entry')], default='MANUAL', max_length=8)),
                ('recorded_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.stop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_events', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_events', to='transport.triplog')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleLocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kmh', models.FloatField(default=0)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('DRIVER_APP', 'Driver Phone App'), ('DEVICE', 'Dedicated GPS Hardware')], default='DRIVER_APP', max_length=16)),
                ('recorded_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='transport.triplog')),
            ],
            options={
                'ordering': ['recorded_at'],
                'indexes': [models.Index(fields=['trip', 'recorded_at'], name='transport_v_trip_id_e96613_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['tenant', 'status'], name='transport_v_tenant__7dd6c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('tenant', 'registration_number')},
        ),
        migrations.AddIndex(
            model_name='triplog',
            index=models.Index(fields=['tenant', 'date', 'status'], name='transport_t_tenant__c337ea_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttransportassignment',
            index=models.Index(fields=['tenant', 'active'], name='transport_s_tenant__6832ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stop',
            unique_together={('route', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='routedeviationalert',
            index=models.Index(fields=['tenant', 'resolved'], name='transport_r_tenant__c04ca3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='boardingevent',
            index=models.Index(fields=['trip', 'student'], name='transport_b_trip_id_7d97e0_idx'),
        ),
    ]
