# Generated by Django 4.2.30 on 2026-07-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studenttransportassignment',
            new_name='transport_s_tenant__ca2010_idx',
            old_name='transport_s_tenant__6832ac_idx',
        ),
        migrations.AlterField(
            model_name='studenttransportassignment',
            name='active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AlterModelTable(
            name='studenttransportassignment',
            table='transport_student_assignment',
        ),
    ]
