# Generated by Django 4.2.30 on 2026-08-21 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        #('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Used for the network admin portal subdomain, e.g. agakhan.asms.app.', max_length=100, unique=True)),
                ('type', models.CharField(choices=[('PRIVATE_GROUP', 'Private group'), ('GOVERNMENT_DISTRICT', 'Government district')], default='PRIVATE_GROUP', max_length=32)),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                               ('plan', models.CharField(choices=[('trial', 'Free Trial'), ('starter', 'Starter (≤300 students)'), ('growth', 'Growth (≤800 students)'), ('professional', 'Professional (≤2000 students)'), ('network', 'Network / School Group'), ('government', 'Government / EMIS')], default='network', help_text="The network's own consolidated plan (Section 5.1 Network plan). Same catalogue as Tenant.plan / platform_billing.Plan.slug.", max_length=20)),
                ('billing_status', models.CharField(choices=[('trial', 'Trial')], default='trial', max_length=20)),
                ('plan_end', models.DateTimeField(blank=True, null=True)),
                ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Networks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('joined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to='networks.network')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_membership_history', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Network membership record',
                'verbose_name_plural': 'Network membership records',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkAdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='networks.network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_admin_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Network admin',
                'verbose_name_plural': 'Network admins',
            },
        ),
        migrations.AddConstraint(
            model_name='networkadminrole',
            constraint=models.UniqueConstraint(fields=('network', 'user'), name='unique_network_admin_per_user'),
        ),
    ]
