# Generated by Django 6.1 on 2026-08-25 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('networks', '0002_networkquerylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('metric', models.CharField(choices=[('ENROLLMENT_COUNT', 'Enrollment count'), ('ATTENDANCE_RATE', 'Attendance rate'), ('FEE_COLLECTION_RATE', 'Fee collection rate'), ('EXAM_PASS_RATE', 'Exam pass rate')], max_length=32)),
                ('value', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='networks.network')),
                ('tenant', models.ForeignKey(blank=True, help_text='Null = network-wide total for this date and metric.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Network daily metric',
                'verbose_name_plural': 'Network daily metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['network', 'metric', 'date'], name='networks_ne_network_8a6789_idx')],
                'constraints': [models.UniqueConstraint(fields=('network', 'tenant', 'date', 'metric'), name='unique_network_metric_per_day')],
            },
        ),
    ]
