# Generated by Django 4.2.30 on 2026-09-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0003_networkdailymetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='billing_status',
            field=models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('grace_period', 'Grace Period'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20),
        ),
    ]
