# Generated by Django 4.2.30 on 2026-06-13 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('form_type', models.CharField(choices=[('school_trip', 'School Trip / Excursion'), ('photo_consent', 'Photography / Media Consent'), ('medical_treatment', 'Medical Treatment Consent'), ('data_processing', 'Data Processing Consent'), ('activity', 'Activity Participation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_consent_forms', to=settings.AUTH_USER_MODEL)),
                ('target_classes', models.ManyToManyField(blank=True, to='students.classroom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParentMeetingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('academic_progress', 'Academic Progress Discussion'), ('behaviour_concern', 'Behaviour / Discipline Concern'), ('welfare_check', 'Welfare / Wellbeing Check-in'), ('fee_discussion', 'Fee / Financial Discussion'), ('general', 'General / Other'), ('special_needs', 'Special Educational Needs'), ('transition', 'Transition / Subject Choice')], default='general', max_length=30)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=20)),
                ('location', models.CharField(blank=True, default='School Office', max_length=100)),
                ('video_link', models.URLField(blank=True, help_text='Zoom/Meet link if online meeting')),
                ('parent_notes', models.TextField(blank=True, help_text='What the parent wants to discuss')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for staff')),
                ('meeting_minutes', models.TextField(blank=True, help_text='Summary recorded after meeting')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'Parent Did Not Attend')], default='pending', max_length=15)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parent_rating', models.PositiveIntegerField(blank=True, help_text='1–5 stars', null=True)),
                ('parent_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_bookings', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_bookings', to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_slots', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-preferred_date', '-preferred_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('announcement', 'Class Announcement'), ('achievement', 'Student Achievement'), ('reminder', 'Homework / Reminder'), ('photo_update', 'Photo Update'), ('event', 'Upcoming Event'), ('resource', 'Learning Resource'), ('health_update', 'Health / Safety Update')], default='announcement', max_length=20)),
                ('audience', models.CharField(choices=[('class', 'Whole Class'), ('student', 'Specific Student (and parent)'), ('school', 'Whole School')], default='class', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_posts/%Y/%m/')),
                ('image_url', models.URLField(blank=True)),
                ('action_link', models.URLField(blank=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_posts', to='students.classroom')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_posts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_posts', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceExcuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence_date', models.DateField()),
                ('absence_date_end', models.DateField(blank=True, help_text='For multi-day absences', null=True)),
                ('excuse_type', models.CharField(choices=[('illness', 'Illness / Medical'), ('family_emergency', 'Family Emergency'), ('bereavement', 'Bereavement'), ('medical_appointment', 'Medical / Dental Appointment'), ('religious', 'Religious Observance'), ('travel', 'Family Travel'), ('other', 'Other')], max_length=30)),
                ('explanation', models.TextField()),
                ('supporting_doc', models.FileField(blank=True, help_text='Medical certificate, etc.', null=True, upload_to='excuses/%Y/%m/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted — Awaiting Review'), ('approved', 'Approved by School'), ('rejected', 'Rejected')], default='submitted', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('school_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excuses', to='attendance.attendancerecord')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_excuses', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_excuses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_excuses', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-absence_date'],
            },
        ),
        migrations.CreateModel(
            name='ParentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('attendance', 'Attendance Alert'), ('academic', 'Academic / Grades'), ('behaviour', 'Behaviour Incident'), ('merit', 'Merit / Achievement'), ('finance', 'Fee / Payment'), ('welfare', 'Welfare'), ('announcement', 'School Announcement'), ('meeting', 'Meeting'), ('assignment', 'Assignment'), ('system', 'System')], default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('action_url', models.CharField(blank=True, help_text='Portal URL to deep-link to', max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_notifications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_notifications', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent_user', 'is_read'], name='parent_port_parent__ac240e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consented', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='parent_portal.consentform')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_responses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_responses', to='students.student')),
            ],
            options={
                'unique_together': {('form', 'student')},
            },
        ),
    ]
