# Generated by Django 4.2.30 on 2026-06-12 06:58

import apps.payments.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPNLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_tracking_id', models.CharField(db_index=True, max_length=100)),
                ('order_merchant_reference', models.CharField(blank=True, max_length=100)),
                ('notification_type', models.CharField(blank=True, max_length=50)),
                ('raw_query_string', models.TextField(blank=True, help_text='Full raw query string from PesaPal IPN GET request')),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PesaPalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_reference', models.CharField(default=apps.payments.models.generate_merchant_ref, help_text='Our unique reference sent to PesaPal', max_length=50, unique=True)),
                ('order_tracking_id', models.CharField(blank=True, help_text='PesaPal order tracking ID returned on submission', max_length=100)),
                ('redirect_url', models.URLField(blank=True, help_text='PesaPal redirect URL where parent completes payment', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('UGX', 'Ugandan Shilling'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar')], default='UGX', max_length=3)),
                ('payer_first_name', models.CharField(blank=True, max_length=100)),
                ('payer_last_name', models.CharField(blank=True, max_length=100)),
                ('payer_phone', models.CharField(blank=True, help_text='Phone number for MTN/Airtel USSD STK push', max_length=20)),
                ('payer_email', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending — Awaiting parent action'), ('completed', 'Completed — Payment confirmed'), ('failed', 'Failed'), ('reversed', 'Reversed / Refunded'), ('cancelled', 'Cancelled by parent'), ('expired', 'Expired — No action taken')], db_index=True, default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='e.g. MTN Mobile Money, Airtel Money, Visa, Mastercard', max_length=50)),
                ('payment_account', models.CharField(blank=True, help_text='Masked phone or card number returned by PesaPal', max_length=100)),
                ('confirmation_code', models.CharField(blank=True, help_text='PesaPal confirmation / receipt code', max_length=100)),
                ('pesapal_status_code', models.IntegerField(blank=True, null=True)),
                ('pesapal_status_message', models.CharField(blank=True, max_length=100)),
                ('submit_response', models.JSONField(blank=True, default=dict)),
                ('status_response', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Transaction expires if no action taken (default: 30 min)', null=True)),
                ('finance_payment', models.OneToOneField(blank=True, help_text='The Payment record created in finance module on confirmation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesapal_transaction', to='finance.payment')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='Staff or parent who started this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesapal_transactions', to='finance.feeinvoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesapal_transactions', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['order_tracking_id'], name='payments_pe_order_t_b17436_idx'), models.Index(fields=['merchant_reference'], name='payments_pe_merchan_38c919_idx'), models.Index(fields=['status'], name='payments_pe_status_9d587a_idx'), models.Index(fields=['invoice'], name='payments_pe_invoice_77044a_idx')],
            },
        ),
    ]
