# Generated by Django 4.2.30 on 2026-08-23 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(help_text="e.g. 'academics.examresult'", max_length=100)),
                ('tenant_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to='networks.network')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Network query log',
                'verbose_name_plural': 'Network query logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
