# Generated by Django 4.2.30 on 2026-08-15 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_tenant_billing_method_tenant_grace_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Must match a Tenant.PlanChoices value exactly (trial/starter/growth/...)', max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('included_students', models.PositiveIntegerField(blank=True, help_text='Students covered by base_price before price_per_extra_student kicks in', null=True)),
                ('max_students', models.PositiveIntegerField(blank=True, help_text='Plan ceiling. Null = no cap (Network/Government).', null=True)),
                ('price_per_extra_student', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_users', models.PositiveIntegerField(blank=True, help_text='Null = unlimited', null=True)),
                ('storage_gb', models.PositiveIntegerField(default=5)),
                ('sms_bundle', models.PositiveIntegerField(default=0, help_text='SMS units included per period')),
                ('sms_overage_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('custom', 'Custom / By Engagement')], default='monthly', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_self_serve', models.BooleanField(default=True, help_text='False for Government/EMIS — those go through sales, not self-onboarding')),
            ],
            options={
                'db_table': 'platform_billing_plan',
                'ordering': ['base_price'],
            },
        ),
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Snapshot of what was owed for this period — does not change if Plan pricing changes later', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='issued', max_length=15)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='platform_billing.plan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'db_table': 'platform_billing_invoice',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='PlatformPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('pesapal_card', 'Card (PesaPal)'), ('mtn_momo', 'MTN Mobile Money'), ('airtel', 'Airtel Money'), ('bank', 'Bank Transfer'), ('manual', 'Manual / Platform Admin')], max_length=15)),
                ('reference', models.CharField(blank=True, help_text='PesaPal order_tracking_id, MoMo ref, etc.', max_length=100)),
                ('is_recurring_charge', models.BooleanField(default=False, help_text='True if this came from PesaPal auto-debit rather than a live checkout')),
                ('raw_gateway_response', models.JSONField(blank=True, default=dict)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='platform_billing.platforminvoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'db_table': 'platform_billing_payment',
                'ordering': ['-payment_date'],
            },
        ),
    ]
