# Generated by Django 4.2.30 on 2026-08-15 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_tenant_billing_method_tenant_grace_started_at_and_more'),
        ('platform_billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPesaPalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=15)),
                ('is_recurring_setup', models.BooleanField(default=False, help_text='True if this order enrolled the tenant in PesaPal card auto-debit')),
                ('order_tracking_id', models.CharField(blank=True, max_length=100)),
                ('redirect_url', models.URLField(blank=True, max_length=500)),
                ('submit_response', models.JSONField(blank=True, default=dict)),
                ('status_response', models.JSONField(blank=True, default=dict)),
                ('pesapal_status_code', models.IntegerField(blank=True, null=True)),
                ('pesapal_status_message', models.CharField(blank=True, max_length=200)),
                ('confirmation_code', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_account', models.CharField(blank=True, max_length=100)),
                ('payer_first_name', models.CharField(blank=True, max_length=100)),
                ('payer_last_name', models.CharField(blank=True, max_length=100)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_transactions_initiated', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesapal_transactions', to='platform_billing.platforminvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'db_table': 'platform_billing_pesapal_transaction',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
