# Generated by Django 4.2.30 on 2026-08-17 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tenant_discount_percent'),
        ('platform_billing', '0002_platformpesapaltransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_name', models.CharField(help_text="e.g. 'lms', 'biometric_attendance', 'career_guidance'", max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'db_table': 'platform_billing_feature_flag',
                'ordering': ['module_name'],
                'unique_together': {('tenant', 'module_name')},
            },
        ),
    ]
