# Generated by Django 4.2.30 on 2026-08-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_billing', '0003_featureflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='included_features',
            field=models.JSONField(blank=True, default=list, help_text='List of short strings shown as checkmarks on the pricing page'),
        ),
        migrations.AddField(
            model_name='plan',
            name='not_included',
            field=models.JSONField(blank=True, default=list, help_text='Honest trade-offs shown on the pricing page — what this tier does NOT cover'),
        ),
    ]
