# Generated by Django 6.1 on 2026-08-25 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_staff'),
        ('networks', '0003_networkdailymetric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('SYLLABUS_TOPIC', 'Syllabus topic'), ('SCHEME_OF_WORK', 'Scheme of work'), ('LESSON_PLAN', 'Lesson plan'), ('QUIZ_BANK', 'Quiz bank')], max_length=32)),
                ('subject', models.CharField(max_length=100)),
                ('level', models.CharField(help_text='Grade/form/year this applies to.', max_length=50)),
                ('content', models.TextField()),
                ('curriculum_source', models.CharField(choices=[('NCDC_ALIGNED', 'NCDC aligned'), ('NETWORK_CUSTOM', 'Network custom')], default='NETWORK_CUSTOM', max_length=32)),
                ('default_locked', models.BooleanField(default=False, help_text='Set by the network when publishing, never by a school. Locked items can never diverge.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from_date', models.DateField(blank=True, help_text="Sync waits until this date — a mid-term publish doesn't retroactively change what an enrolled cohort is already following (NCDC's own rollouts are cohort-staged).", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(blank=True, help_text='Null = platform/NCDC-baseline content, adoptable by any school.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_resources', to='networks.network')),
            ],
            options={
                'verbose_name': 'Curriculum resource',
                'verbose_name_plural': 'Curriculum resources',
                'ordering': ['subject', 'level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumPublishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('synced_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_logs', to='curriculum.curriculumresource')),
            ],
            options={
                'verbose_name': 'Curriculum publish log',
                'verbose_name_plural': 'Curriculum publish logs',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopted_version', models.PositiveIntegerField()),
                ('is_diverged', models.BooleanField(default=False)),
                ('diverged_at', models.DateTimeField(blank=True, null=True)),
                ('local_content', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_adoptions', to='core.tenant')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='curriculum.curriculumresource')),
            ],
            options={
                'verbose_name': 'Curriculum adoption',
                'verbose_name_plural': 'Curriculum adoptions',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'resource'), name='unique_adoption_per_school_resource')],
            },
        ),
    ]
