# Generated by Django 4.2.30 on 2026-05-30 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('trigger', models.CharField(choices=[('attendance', 'Absence Notification'), ('fee', 'Fee Reminder'), ('result', 'Result Published'), ('discipline', 'Discipline Incident'), ('bulk', 'Bulk Announcement'), ('manual', 'Manual / Admin')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_ref', models.CharField(blank=True, help_text="Africa's Talking message ID", max_length=100)),
                ('cost', models.DecimalField(decimal_places=4, default=0, help_text="Cost in USD as billed by Africa's Talking", max_digits=8)),
                ('error_message', models.TextField(blank=True)),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='students.student')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_sent', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'db_table': 'communication_sms_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'Everyone (All Parents & Students)'), ('parents', 'All Parents'), ('students', 'All Students'), ('staff', 'All Staff'), ('class', 'Specific Class')], default='all', max_length=15)),
                ('send_sms', models.BooleanField(default=False, help_text='Also send as SMS to relevant phone numbers')),
                ('is_published', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_date', models.DateTimeField(blank=True, null=True)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_made', to=settings.AUTH_USER_MODEL)),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='students.classroom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'db_table': 'communication_announcement',
                'ordering': ['-publish_date'],
            },
        ),
    ]
