# Generated by Django 4.2.30 on 2026-05-30 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_days', models.PositiveSmallIntegerField(default=0)),
                ('days_present', models.PositiveSmallIntegerField(default=0)),
                ('days_absent', models.PositiveSmallIntegerField(default=0)),
                ('days_late', models.PositiveSmallIntegerField(default=0)),
                ('days_excused', models.PositiveSmallIntegerField(default=0)),
                ('attendance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('consecutive_absences', models.PositiveSmallIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='core.term')),
            ],
            options={
                'db_table': 'attendance_summary',
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late / Tardy'), ('E', 'Excused Absence'), ('S', 'Suspended')], default='P', max_length=1)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('excuse_reason', models.CharField(blank=True, max_length=200)),
                ('parent_notified', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.classroom')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marks', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'db_table': 'attendance_record',
                'ordering': ['-date', 'student__last_name'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
