# Generated by Django 4.2.30 on 2026-07-04 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_profile_verified'),
        ('core', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('ZKTECO', 'ZKTeco'), ('SUPREMA', 'Suprema'), ('ANVIZ', 'Anviz'), ('OTHER', 'Other / Generic')], default='OTHER', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, help_text='e.g. "Main Gate", "Block A Entrance"', max_length=150)),
                ('secret_key', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Under Maintenance')], default='ACTIVE', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_devices', to='students.classroom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Biometric Device',
                'db_table': 'biometric_device',
            },
        ),
        migrations.CreateModel(
            name='BiometricTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_id', models.CharField(help_text='Fingerprint/template ID as issued by the device SDK', max_length=100)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='attendance.biometricdevice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_templates', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Biometric Template',
                'db_table': 'biometric_template',
                'unique_together': {('device', 'template_id')},
            },
        ),
        migrations.CreateModel(
            name='BiometricScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_id_raw', models.CharField(blank=True, max_length=100)),
                ('scanned_at', models.DateTimeField(help_text='Timestamp reported by the device')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When ASMS received it')),
                ('result', models.CharField(choices=[('MATCHED', 'Matched — Attendance Recorded'), ('DUPLICATE', 'Duplicate Scan (already marked today)'), ('UNKNOWN', 'Unknown Template ID'), ('OUT_OF_WINDOW', 'Outside Attendance Window'), ('INVALID_SIG', 'Invalid Signature — Rejected')], max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_scans', to='attendance.attendancerecord')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='attendance.biometricdevice')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_scans', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Biometric Scan Log',
                'db_table': 'biometric_scan_log',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['device', 'received_at'], name='biometric_s_device__cac99a_idx'), models.Index(fields=['student', 'scanned_at'], name='biometric_s_student_c6a9b9_idx')],
            },
        ),
    ]
