"""
ASMS Student Management Module
The Student model is the heart of the system.
All other modules reference it.
"""

from django.db import models
from django.utils import timezone
from apps.core.models import TenantModel


class ClassLevel(TenantModel):
    """
    Represents a year group: e.g. Primary 1, Senior 1, Baby Class.
    """
    name         = models.CharField(max_length=50, verbose_name='Class Level Name')
    short_name   = models.CharField(max_length=10, blank=True, verbose_name='Short Name e.g. P1')
    order        = models.PositiveSmallIntegerField(default=0, help_text='Sort order')
    category     = models.CharField(max_length=20, choices=[
        ('nursery',   'Nursery / Pre-Primary'),
        ('primary',   'Primary'),
        ('secondary', 'Secondary / High School'),
        ('college',   'College / University'),
    ], default='primary')

    class Meta:
        db_table        = 'students_class_level'
        ordering        = ['order', 'name']
        unique_together = [('tenant', 'name')]
        verbose_name    = 'Class Level'

    def __str__(self):
        return self.name


class ClassRoom(TenantModel):
    """
    A specific class section: e.g. Senior 2 East, Primary 3 Blue.
    This is what students are enrolled in and teachers are assigned to.
    """
    level        = models.ForeignKey(ClassLevel, on_delete=models.PROTECT,
                                     related_name='classrooms')
    stream       = models.CharField(max_length=20, blank=True,
                                    help_text='e.g. East, Blue, A, North')
    academic_year = models.ForeignKey('core.AcademicYear', on_delete=models.PROTECT,
                                      related_name='classrooms')
    class_teacher = models.ForeignKey('accounts.User', on_delete=models.SET_NULL,
                                      null=True, blank=True, related_name='class_teacher_of',
                                      limit_choices_to={'role': 'teacher'})
    capacity     = models.PositiveSmallIntegerField(default=45)

    class Meta:
        db_table        = 'students_classroom'
        ordering        = ['level__order', 'stream']
        unique_together = [('tenant', 'level', 'stream', 'academic_year')]
        verbose_name    = 'Classroom'

    def __str__(self):
        stream = f' {self.stream}' if self.stream else ''
        return f'{self.level.name}{stream}'

    def get_full_name(self):
        return str(self)

    def student_count(self):
        return self.enrollments.filter(is_active=True).count()


class Student(TenantModel):
    """
    The central student record. Every other module references this.
    Includes all fields required by EMIS/government reporting.
    """

    class GenderChoices(models.TextChoices):
        MALE   = 'M', 'Male'
        FEMALE = 'F', 'Female'
        OTHER  = 'O', 'Other / Prefer not to say'

    class StatusChoices(models.TextChoices):
        ACTIVE    = 'active',    'Active / Enrolled'
        INACTIVE  = 'inactive',  'Inactive'
        GRADUATED = 'graduated', 'Graduated'
        WITHDRAWN = 'withdrawn', 'Withdrawn'
        EXPELLED  = 'expelled',  'Expelled'
        DECEASED  = 'deceased',  'Deceased'
        DEFERRED  = 'deferred',  'Deferred'

    class ReligionChoices(models.TextChoices):
        CHRISTIAN = 'christian', 'Christian'
        MUSLIM    = 'muslim',    'Muslim'
        OTHER     = 'other',     'Other'
        NONE      = 'none',      'None / Not stated'

    # ── Identity ─────────────────────────────────────────────────
    student_id   = models.CharField(max_length=20, verbose_name='Student ID',
                                    help_text='Auto-generated by school format')
    first_name   = models.CharField(max_length=100)
    middle_name  = models.CharField(max_length=100, blank=True)
    last_name    = models.CharField(max_length=100)
    preferred_name = models.CharField(max_length=100, blank=True,
                                      help_text='Name used daily if different')

    # ── EMIS / National IDs ───────────────────────────────────────
    nsin         = models.CharField(max_length=50, blank=True,
                                    verbose_name='National Student Identification Number (NSIN)')
    birth_cert_number = models.CharField(max_length=50, blank=True)

    # ── Demographics (required for EMIS census) ───────────────────
    date_of_birth = models.DateField(null=True, blank=True)
    gender        = models.CharField(max_length=1, choices=GenderChoices.choices,
                                     default=GenderChoices.MALE)
    nationality   = models.CharField(max_length=50, default='Ugandan')
    religion      = models.CharField(max_length=20, choices=ReligionChoices.choices,
                                     blank=True)
    home_district = models.CharField(max_length=100, blank=True)
    home_village  = models.CharField(max_length=100, blank=True)

    # ── EMIS Special Flags ────────────────────────────────────────
    has_disability       = models.BooleanField(default=False)
    disability_type      = models.CharField(max_length=100, blank=True)
    is_orphan            = models.BooleanField(default=False)
    orphan_type          = models.CharField(max_length=20, blank=True, choices=[
        ('both',    'Double Orphan (both parents)'),
        ('father',  'Paternal Orphan'),
        ('mother',  'Maternal Orphan'),
    ])
    is_refugee           = models.BooleanField(default=False)
    receives_bursary     = models.BooleanField(default=False)

    # ── Medical ───────────────────────────────────────────────────
    blood_group  = models.CharField(max_length=5, blank=True,
                                    choices=[('A+','A+'),('A-','A-'),('B+','B+'),('B-','B-'),
                                             ('AB+','AB+'),('AB-','AB-'),('O+','O+'),('O-','O-')])
    allergies    = models.TextField(blank=True)
    medical_notes = models.TextField(blank=True,
                                     help_text='Any chronic conditions or medication requirements')

    # ── Contact ───────────────────────────────────────────────────
    student_phone = models.CharField(max_length=20, blank=True,
                                     help_text='Student\'s own phone (secondary only)')
    student_email = models.EmailField(blank=True)

    # ── Photo ─────────────────────────────────────────────────────
    photo        = models.ImageField(upload_to='students/photos/', null=True, blank=True)

    # ── Status ────────────────────────────────────────────────────
    status       = models.CharField(max_length=15, choices=StatusChoices.choices,
                                    default=StatusChoices.ACTIVE)
    admission_date = models.DateField(default=timezone.now)
    exit_date    = models.DateField(null=True, blank=True)
    exit_reason  = models.TextField(blank=True)

    # ── Linked User Account ───────────────────────────────────────
    user         = models.OneToOneField(
        'accounts.User', on_delete=models.SET_NULL,
        null=True, blank=True, related_name='student_profile',
        help_text='Portal login account for this student'
    )

    class Meta:
        db_table            = 'students_student'
        ordering            = ['last_name', 'first_name']
        unique_together     = [('tenant', 'student_id')]
        verbose_name        = 'Student'
        verbose_name_plural = 'Students'

    def __str__(self):
        return f'{self.get_full_name()} ({self.student_id})'

    def get_full_name(self):
        parts = [self.first_name, self.middle_name, self.last_name]
        return ' '.join(p for p in parts if p).strip()

    def get_display_name(self):
        return self.preferred_name or self.first_name

    def age(self):
        if self.date_of_birth:
            today = timezone.now().date()
            dob = self.date_of_birth
            return today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))
        return None

    def current_class(self):
        enrollment = self.enrollments.filter(is_active=True).select_related('classroom').first()
        return enrollment.classroom if enrollment else None


class Enrollment(TenantModel):
    """
    Links a Student to a ClassRoom for a specific AcademicYear.
    A student has one active enrollment at a time.
    Previous enrollments are kept for history.
    """
    student      = models.ForeignKey(Student, on_delete=models.CASCADE,
                                     related_name='enrollments')
    classroom    = models.ForeignKey(ClassRoom, on_delete=models.PROTECT,
                                     related_name='enrollments')
    academic_year = models.ForeignKey('core.AcademicYear', on_delete=models.PROTECT,
                                      related_name='enrollments')
    enrolled_date = models.DateField(default=timezone.now)
    is_active    = models.BooleanField(default=True)
    is_repeating = models.BooleanField(default=False,
                                       help_text='True if student is repeating this class level')
    notes        = models.TextField(blank=True)

    class Meta:
        db_table        = 'students_enrollment'
        ordering        = ['-academic_year__start_date']
        unique_together = [('student', 'academic_year')]

    def __str__(self):
        return f'{self.student} → {self.classroom} ({self.academic_year.name})'


class Guardian(TenantModel):
    """
    Parent or guardian of a student.
    One guardian can be linked to multiple students (family).
    """

    class RelationshipChoices(models.TextChoices):
        FATHER      = 'father',      'Father'
        MOTHER      = 'mother',      'Mother'
        GRANDFATHER = 'grandfather', 'Grandfather'
        GRANDMOTHER = 'grandmother', 'Grandmother'
        UNCLE       = 'uncle',       'Uncle'
        AUNT        = 'aunt',        'Aunt'
        SIBLING     = 'sibling',     'Older Sibling'
        GUARDIAN    = 'guardian',    'Legal Guardian'
        OTHER       = 'other',       'Other'

    student      = models.ForeignKey(Student, on_delete=models.CASCADE,
                                     related_name='guardians')
    first_name   = models.CharField(max_length=100)
    last_name    = models.CharField(max_length=100)
    relationship = models.CharField(max_length=20, choices=RelationshipChoices.choices)
    phone_primary   = models.CharField(max_length=20)
    phone_secondary = models.CharField(max_length=20, blank=True)
    email           = models.EmailField(blank=True)
    occupation      = models.CharField(max_length=100, blank=True)
    national_id     = models.CharField(max_length=50, blank=True)
    is_primary      = models.BooleanField(default=False,
                                          help_text='Primary contact for this student')
    is_fee_payer    = models.BooleanField(default=False,
                                          help_text='Responsible for fee payments')
    receives_sms    = models.BooleanField(default=True)
    receives_reports = models.BooleanField(default=True)

    # ── Linked User Account ───────────────────────────────────────
    user         = models.ForeignKey(
        'accounts.User', on_delete=models.SET_NULL,
        null=True, blank=True, related_name='guardian_of',
        help_text='Portal login account for this parent'
    )

    class Meta:
        db_table = 'students_guardian'
        ordering = ['-is_primary', 'last_name']

    def __str__(self):
        return f'{self.first_name} {self.last_name} ({self.get_relationship_display()} of {self.student})'

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'
