# Generated by Django 4.2.30 on 2026-05-30 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('nationality', models.CharField(default='Ugandan', max_length=50)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('previous_class', models.CharField(blank=True, max_length=50)),
                ('previous_school_results', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft / Incomplete'), ('submitted', 'Submitted — Awaiting Review'), ('shortlisted', 'Shortlisted — Interview'), ('accepted', 'Accepted — Offer Made'), ('enrolled', 'Enrolled — Converted to Student'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by Applicant')], default='submitted', max_length=20)),
                ('application_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('offer_expiry', models.DateField(blank=True, null=True)),
                ('applying_for_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='students.classlevel')),
                ('applying_for_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.academicyear')),
                ('converted_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='students.student')),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_decisions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Admission Application',
                'db_table': 'admissions_application',
                'ordering': ['-applied_date'],
            },
        ),
    ]
