# Generated by Django 4.2.30 on 2026-06-21 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EMISSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_template', models.CharField(choices=[('uganda_moes', 'Uganda MoES'), ('kenya_moe', 'Kenya MoE (NEMIS)'), ('rwanda_reb', 'Rwanda REB'), ('tanzania_moevt', 'Tanzania MoEVT')], default='uganda_moes', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.CharField(blank=True, help_text='Storage path / URL to the generated CSV/ZIP file', max_length=500)),
                ('status', models.CharField(choices=[('generated', 'Export Generated'), ('submitted', 'Submitted to Ministry'), ('acknowledged', 'Acknowledged by Ministry')], default='generated', max_length=15)),
                ('submission_reference', models.CharField(blank=True, help_text='Reference number provided by the ministry on receipt', max_length=100)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('compliance_issues', models.JSONField(blank=True, default=list, help_text='List of compliance warnings detected at export time (missing NSINs, etc.)')),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emis_submissions', to='core.academicyear')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emis_exports_generated', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emis_exports_submitted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'EMIS Submission',
                'db_table': 'emis_submission',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolInfrastructureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_classrooms', models.PositiveSmallIntegerField(default=0)),
                ('functional_classrooms', models.PositiveSmallIntegerField(default=0)),
                ('has_electricity', models.BooleanField(default=False)),
                ('has_piped_water', models.BooleanField(default=False)),
                ('has_borehole', models.BooleanField(default=False)),
                ('has_internet', models.BooleanField(default=False)),
                ('internet_type', models.CharField(blank=True, help_text='e.g. Fibre, 4G LTE, Satellite, WiMAX', max_length=50)),
                ('toilet_blocks_boys', models.PositiveSmallIntegerField(default=0)),
                ('toilet_blocks_girls', models.PositiveSmallIntegerField(default=0)),
                ('toilet_blocks_teachers', models.PositiveSmallIntegerField(default=0)),
                ('has_library', models.BooleanField(default=False)),
                ('library_books', models.PositiveIntegerField(default=0)),
                ('has_laboratory', models.BooleanField(default=False)),
                ('lab_count', models.PositiveSmallIntegerField(default=0)),
                ('has_computer_lab', models.BooleanField(default=False)),
                ('computer_count', models.PositiveSmallIntegerField(default=0)),
                ('has_sports_field', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infrastructure_records', to='core.academicyear')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_records_updated', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'School Infrastructure Record',
                'db_table': 'emis_infrastructure_record',
                'unique_together': {('tenant', 'academic_year')},
            },
        ),
    ]
