# Generated by Django 4.2.30 on 2026-08-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissubmission',
            name='country_template',
            field=models.CharField(choices=[('uganda_moes', 'Uganda (MoES)'), ('kenya_moe', 'Kenya (MoE / KEMIS)'), ('rwanda_reb', 'Rwanda (REB)'), ('tanzania_moevt', 'Tanzania (MoEST / ESMIS)')], default='uganda_moes', max_length=20),
        ),
    ]
