# Generated by Django 4.2.30 on 2026-07-04 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_e164', models.CharField(db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('rate_limited', 'Rate limited'), ('invalid_number', 'Invalid number'), ('duplicate_suppressed', 'Duplicate suppressed')], db_index=True, max_length=24)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('cost', models.CharField(blank=True, max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('attempt_log', models.JSONField(blank=True, default=list)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='notificatio_tenant__3901d8_idx'), models.Index(fields=['provider', 'status'], name='notificatio_provide_64425b_idx')],
            },
        ),
    ]
